#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
   echo "USAGE: gh mfem-merge-into-next <pr-number>"
   exit 1
fi


if [ -n "$(git status --porcelain)" ]; then
   echo "Must merge with clean working directory"
   exit 1
fi

git checkout next
git pull

pr_owner=$(gh pr view $1 --json headRepositoryOwner --jq ".headRepositoryOwner.login")
pr_branch=$(gh pr view $1 --json headRefName --jq '.headRefName')

if [ "$pr_owner" == "mfem" ]; then
   pr_from="$pr_branch"
else
   pr_from="$pr_owner:$pr_branch"
fi

commit_msg="Merge branch '$pr_from' into next (PR #$1)"

tmp_branch=gh/pr/$1
git fetch origin pull/$1/head:$tmp_branch
git merge $tmp_branch -m "$commit_msg"
git branch -D $tmp_branch

if git diff --exit-code origin/next; then
   echo
   echo -e "\033[1;33mNo chages made. Has PR #$1 already been merged into next?\033[0m"
   echo
else
   echo
   echo -e "\033[0;32mMerged PR #$1 [$pr_from] into next with commit message:\033[0m"
   echo
   echo "    $commit_msg"
   echo
   echo -e "\033[0;34mRun 'git push' to push the merge to GitHub.\033[0m"
fi
